// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.1
// source: colmena_consensus/colmena_consensus.proto

package colmena_consensus

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SchedulingService_TriggerRole_FullMethodName = "/colmena_consensus.SchedulingService/TriggerRole"
)

// SchedulingServiceClient is the client API for SchedulingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchedulingServiceClient interface {
	TriggerRole(ctx context.Context, in *TriggerRoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type schedulingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulingServiceClient(cc grpc.ClientConnInterface) SchedulingServiceClient {
	return &schedulingServiceClient{cc}
}

func (c *schedulingServiceClient) TriggerRole(ctx context.Context, in *TriggerRoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SchedulingService_TriggerRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulingServiceServer is the server API for SchedulingService service.
// All implementations must embed UnimplementedSchedulingServiceServer
// for forward compatibility.
type SchedulingServiceServer interface {
	TriggerRole(context.Context, *TriggerRoleRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedSchedulingServiceServer()
}

// UnimplementedSchedulingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchedulingServiceServer struct{}

func (UnimplementedSchedulingServiceServer) TriggerRole(context.Context, *TriggerRoleRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerRole not implemented")
}
func (UnimplementedSchedulingServiceServer) mustEmbedUnimplementedSchedulingServiceServer() {}
func (UnimplementedSchedulingServiceServer) testEmbeddedByValue()                           {}

// UnsafeSchedulingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulingServiceServer will
// result in compilation errors.
type UnsafeSchedulingServiceServer interface {
	mustEmbedUnimplementedSchedulingServiceServer()
}

func RegisterSchedulingServiceServer(s grpc.ServiceRegistrar, srv SchedulingServiceServer) {
	// If the following call pancis, it indicates UnimplementedSchedulingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SchedulingService_ServiceDesc, srv)
}

func _SchedulingService_TriggerRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).TriggerRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_TriggerRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).TriggerRole(ctx, req.(*TriggerRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SchedulingService_ServiceDesc is the grpc.ServiceDesc for SchedulingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchedulingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "colmena_consensus.SchedulingService",
	HandlerType: (*SchedulingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TriggerRole",
			Handler:    _SchedulingService_TriggerRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "colmena_consensus/colmena_consensus.proto",
}

const (
	SelectionService_RequestRoles_FullMethodName = "/colmena_consensus.SelectionService/RequestRoles"
)

// SelectionServiceClient is the client API for SelectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SelectionServiceClient interface {
	RequestRoles(ctx context.Context, in *RoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type selectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSelectionServiceClient(cc grpc.ClientConnInterface) SelectionServiceClient {
	return &selectionServiceClient{cc}
}

func (c *selectionServiceClient) RequestRoles(ctx context.Context, in *RoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SelectionService_RequestRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SelectionServiceServer is the server API for SelectionService service.
// All implementations must embed UnimplementedSelectionServiceServer
// for forward compatibility.
type SelectionServiceServer interface {
	RequestRoles(context.Context, *RoleRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedSelectionServiceServer()
}

// UnimplementedSelectionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSelectionServiceServer struct{}

func (UnimplementedSelectionServiceServer) RequestRoles(context.Context, *RoleRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestRoles not implemented")
}
func (UnimplementedSelectionServiceServer) mustEmbedUnimplementedSelectionServiceServer() {}
func (UnimplementedSelectionServiceServer) testEmbeddedByValue()                          {}

// UnsafeSelectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SelectionServiceServer will
// result in compilation errors.
type UnsafeSelectionServiceServer interface {
	mustEmbedUnimplementedSelectionServiceServer()
}

func RegisterSelectionServiceServer(s grpc.ServiceRegistrar, srv SelectionServiceServer) {
	// If the following call pancis, it indicates UnimplementedSelectionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SelectionService_ServiceDesc, srv)
}

func _SelectionService_RequestRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SelectionServiceServer).RequestRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SelectionService_RequestRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SelectionServiceServer).RequestRoles(ctx, req.(*RoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SelectionService_ServiceDesc is the grpc.ServiceDesc for SelectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SelectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "colmena_consensus.SelectionService",
	HandlerType: (*SelectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestRoles",
			Handler:    _SelectionService_RequestRoles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "colmena_consensus/colmena_consensus.proto",
}
