// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.26.1
// source: colmena_consensus/colmena_consensus.proto

package colmena_consensus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	StartOrStop   bool                   `protobuf:"varint,2,opt,name=startOrStop,proto3" json:"startOrStop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleRequest) Reset() {
	*x = RoleRequest{}
	mi := &file_colmena_consensus_colmena_consensus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleRequest) ProtoMessage() {}

func (x *RoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_colmena_consensus_colmena_consensus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleRequest.ProtoReflect.Descriptor instead.
func (*RoleRequest) Descriptor() ([]byte, []int) {
	return file_colmena_consensus_colmena_consensus_proto_rawDescGZIP(), []int{0}
}

func (x *RoleRequest) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *RoleRequest) GetStartOrStop() bool {
	if x != nil {
		return x.StartOrStop
	}
	return false
}

type TriggerRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	StartOrStop   bool                   `protobuf:"varint,3,opt,name=startOrStop,proto3" json:"startOrStop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRoleRequest) Reset() {
	*x = TriggerRoleRequest{}
	mi := &file_colmena_consensus_colmena_consensus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRoleRequest) ProtoMessage() {}

func (x *TriggerRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_colmena_consensus_colmena_consensus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRoleRequest.ProtoReflect.Descriptor instead.
func (*TriggerRoleRequest) Descriptor() ([]byte, []int) {
	return file_colmena_consensus_colmena_consensus_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *TriggerRoleRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *TriggerRoleRequest) GetStartOrStop() bool {
	if x != nil {
		return x.StartOrStop
	}
	return false
}

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	Resources     []*Resource            `protobuf:"bytes,3,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_colmena_consensus_colmena_consensus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_colmena_consensus_colmena_consensus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_colmena_consensus_colmena_consensus_proto_rawDescGZIP(), []int{2}
}

func (x *Role) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *Role) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *Role) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float32                `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_colmena_consensus_colmena_consensus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_colmena_consensus_colmena_consensus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_colmena_consensus_colmena_consensus_proto_rawDescGZIP(), []int{3}
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_colmena_consensus_colmena_consensus_proto protoreflect.FileDescriptor

const file_colmena_consensus_colmena_consensus_proto_rawDesc = "" +
	"\n" +
	")colmena_consensus/colmena_consensus.proto\x12\x11colmena_consensus\x1a\x1bgoogle/protobuf/empty.proto\"\\\n" +
	"\vRoleRequest\x12+\n" +
	"\x04role\x18\x01 \x01(\v2\x17.colmena_consensus.RoleR\x04role\x12 \n" +
	"\vstartOrStop\x18\x02 \x01(\bR\vstartOrStop\"l\n" +
	"\x12TriggerRoleRequest\x12\x16\n" +
	"\x06roleId\x18\x01 \x01(\tR\x06roleId\x12\x1c\n" +
	"\tserviceId\x18\x02 \x01(\tR\tserviceId\x12 \n" +
	"\vstartOrStop\x18\x03 \x01(\bR\vstartOrStop\"w\n" +
	"\x04Role\x12\x16\n" +
	"\x06roleId\x18\x01 \x01(\tR\x06roleId\x12\x1c\n" +
	"\tserviceId\x18\x02 \x01(\tR\tserviceId\x129\n" +
	"\tresources\x18\x03 \x03(\v2\x1b.colmena_consensus.ResourceR\tresources\"4\n" +
	"\bResource\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value2a\n" +
	"\x11SchedulingService\x12L\n" +
	"\vTriggerRole\x12%.colmena_consensus.TriggerRoleRequest\x1a\x16.google.protobuf.Empty2Z\n" +
	"\x10SelectionService\x12F\n" +
	"\fRequestRoles\x12\x1e.colmena_consensus.RoleRequest\x1a\x16.google.protobuf.EmptyB\x15Z\x13./colmena_consensusb\x06proto3"

var (
	file_colmena_consensus_colmena_consensus_proto_rawDescOnce sync.Once
	file_colmena_consensus_colmena_consensus_proto_rawDescData []byte
)

func file_colmena_consensus_colmena_consensus_proto_rawDescGZIP() []byte {
	file_colmena_consensus_colmena_consensus_proto_rawDescOnce.Do(func() {
		file_colmena_consensus_colmena_consensus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_colmena_consensus_colmena_consensus_proto_rawDesc), len(file_colmena_consensus_colmena_consensus_proto_rawDesc)))
	})
	return file_colmena_consensus_colmena_consensus_proto_rawDescData
}

var file_colmena_consensus_colmena_consensus_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_colmena_consensus_colmena_consensus_proto_goTypes = []any{
	(*RoleRequest)(nil),        // 0: colmena_consensus.RoleRequest
	(*TriggerRoleRequest)(nil), // 1: colmena_consensus.TriggerRoleRequest
	(*Role)(nil),               // 2: colmena_consensus.Role
	(*Resource)(nil),           // 3: colmena_consensus.Resource
	(*emptypb.Empty)(nil),      // 4: google.protobuf.Empty
}
var file_colmena_consensus_colmena_consensus_proto_depIdxs = []int32{
	2, // 0: colmena_consensus.RoleRequest.role:type_name -> colmena_consensus.Role
	3, // 1: colmena_consensus.Role.resources:type_name -> colmena_consensus.Resource
	1, // 2: colmena_consensus.SchedulingService.TriggerRole:input_type -> colmena_consensus.TriggerRoleRequest
	0, // 3: colmena_consensus.SelectionService.RequestRoles:input_type -> colmena_consensus.RoleRequest
	4, // 4: colmena_consensus.SchedulingService.TriggerRole:output_type -> google.protobuf.Empty
	4, // 5: colmena_consensus.SelectionService.RequestRoles:output_type -> google.protobuf.Empty
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_colmena_consensus_colmena_consensus_proto_init() }
func file_colmena_consensus_colmena_consensus_proto_init() {
	if File_colmena_consensus_colmena_consensus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_colmena_consensus_colmena_consensus_proto_rawDesc), len(file_colmena_consensus_colmena_consensus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_colmena_consensus_colmena_consensus_proto_goTypes,
		DependencyIndexes: file_colmena_consensus_colmena_consensus_proto_depIdxs,
		MessageInfos:      file_colmena_consensus_colmena_consensus_proto_msgTypes,
	}.Build()
	File_colmena_consensus_colmena_consensus_proto = out.File
	file_colmena_consensus_colmena_consensus_proto_goTypes = nil
	file_colmena_consensus_colmena_consensus_proto_depIdxs = nil
}
