/*
 *  Copyright 2002-2024 Barcelona Supercomputing Center (www.bsc.es)
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: grpc/routes.proto

package grpc

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ThresholdType int32

const (
	ThresholdType_GREATER_THAN_OR_EQUAL_TO ThresholdType = 0
	ThresholdType_LESS_THAN                ThresholdType = 1
)

// Enum value maps for ThresholdType.
var (
	ThresholdType_name = map[int32]string{
		0: "GREATER_THAN_OR_EQUAL_TO",
		1: "LESS_THAN",
	}
	ThresholdType_value = map[string]int32{
		"GREATER_THAN_OR_EQUAL_TO": 0,
		"LESS_THAN":                1,
	}
)

func (x ThresholdType) Enum() *ThresholdType {
	p := new(ThresholdType)
	*p = x
	return p
}

func (x ThresholdType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThresholdType) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_routes_proto_enumTypes[0].Descriptor()
}

func (ThresholdType) Type() protoreflect.EnumType {
	return &file_grpc_routes_proto_enumTypes[0]
}

func (x ThresholdType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThresholdType.Descriptor instead.
func (ThresholdType) EnumDescriptor() ([]byte, []int) {
	return file_grpc_routes_proto_rawDescGZIP(), []int{0}
}

type HardwareRequirement int32

const (
	HardwareRequirement_CAMERA HardwareRequirement = 0
	HardwareRequirement_CPU    HardwareRequirement = 1
)

// Enum value maps for HardwareRequirement.
var (
	HardwareRequirement_name = map[int32]string{
		0: "CAMERA",
		1: "CPU",
	}
	HardwareRequirement_value = map[string]int32{
		"CAMERA": 0,
		"CPU":    1,
	}
)

func (x HardwareRequirement) Enum() *HardwareRequirement {
	p := new(HardwareRequirement)
	*p = x
	return p
}

func (x HardwareRequirement) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HardwareRequirement) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_routes_proto_enumTypes[1].Descriptor()
}

func (HardwareRequirement) Type() protoreflect.EnumType {
	return &file_grpc_routes_proto_enumTypes[1]
}

func (x HardwareRequirement) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HardwareRequirement.Descriptor instead.
func (HardwareRequirement) EnumDescriptor() ([]byte, []int) {
	return file_grpc_routes_proto_rawDescGZIP(), []int{1}
}

type TimeUnit int32

const (
	TimeUnit_SECONDS TimeUnit = 0
	TimeUnit_MINUTES TimeUnit = 1
	TimeUnit_HOURS   TimeUnit = 2
)

// Enum value maps for TimeUnit.
var (
	TimeUnit_name = map[int32]string{
		0: "SECONDS",
		1: "MINUTES",
		2: "HOURS",
	}
	TimeUnit_value = map[string]int32{
		"SECONDS": 0,
		"MINUTES": 1,
		"HOURS":   2,
	}
)

func (x TimeUnit) Enum() *TimeUnit {
	p := new(TimeUnit)
	*p = x
	return p
}

func (x TimeUnit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeUnit) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_routes_proto_enumTypes[2].Descriptor()
}

func (TimeUnit) Type() protoreflect.EnumType {
	return &file_grpc_routes_proto_enumTypes[2]
}

func (x TimeUnit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeUnit.Descriptor instead.
func (TimeUnit) EnumDescriptor() ([]byte, []int) {
	return file_grpc_routes_proto_rawDescGZIP(), []int{2}
}

type StorageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StorageRequest) Reset() {
	*x = StorageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_routes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageRequest) ProtoMessage() {}

func (x *StorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_routes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageRequest.ProtoReflect.Descriptor instead.
func (*StorageRequest) Descriptor() ([]byte, []int) {
	return file_grpc_routes_proto_rawDescGZIP(), []int{0}
}

func (x *StorageRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StorageRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type MetricsStorageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string               `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value     float64              `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *MetricsStorageRequest) Reset() {
	*x = MetricsStorageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_routes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricsStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsStorageRequest) ProtoMessage() {}

func (x *MetricsStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_routes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsStorageRequest.ProtoReflect.Descriptor instead.
func (*MetricsStorageRequest) Descriptor() ([]byte, []int) {
	return file_grpc_routes_proto_rawDescGZIP(), []int{1}
}

func (x *MetricsStorageRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MetricsStorageRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricsStorageRequest) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type GetStoredRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetStoredRequest) Reset() {
	*x = GetStoredRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_routes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStoredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoredRequest) ProtoMessage() {}

func (x *GetStoredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_routes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoredRequest.ProtoReflect.Descriptor instead.
func (*GetStoredRequest) Descriptor() ([]byte, []int) {
	return file_grpc_routes_proto_rawDescGZIP(), []int{2}
}

func (x *GetStoredRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetStoredResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetStoredResponse) Reset() {
	*x = GetStoredResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_routes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStoredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoredResponse) ProtoMessage() {}

func (x *GetStoredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_routes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoredResponse.ProtoReflect.Descriptor instead.
func (*GetStoredResponse) Descriptor() ([]byte, []int) {
	return file_grpc_routes_proto_rawDescGZIP(), []int{3}
}

func (x *GetStoredResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type CommunicationChannelsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *CommunicationChannelsRequest) Reset() {
	*x = CommunicationChannelsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_routes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunicationChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunicationChannelsRequest) ProtoMessage() {}

func (x *CommunicationChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_routes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunicationChannelsRequest.ProtoReflect.Descriptor instead.
func (*CommunicationChannelsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_routes_proto_rawDescGZIP(), []int{4}
}

func (x *CommunicationChannelsRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CommunicationChannelsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key                                string                                `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	CommunicationChannels              []*CommunicationChannel               `protobuf:"bytes,2,rep,name=communicationChannels,proto3" json:"communicationChannels,omitempty"`
	ColmenaStorageCommunicationChannel []*ColmenaStorageCommunicationChannel `protobuf:"bytes,3,rep,name=colmenaStorageCommunicationChannel,proto3" json:"colmenaStorageCommunicationChannel,omitempty"`
}

func (x *CommunicationChannelsResponse) Reset() {
	*x = CommunicationChannelsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_routes_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunicationChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunicationChannelsResponse) ProtoMessage() {}

func (x *CommunicationChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_routes_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunicationChannelsResponse.ProtoReflect.Descriptor instead.
func (*CommunicationChannelsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_routes_proto_rawDescGZIP(), []int{5}
}

func (x *CommunicationChannelsResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CommunicationChannelsResponse) GetCommunicationChannels() []*CommunicationChannel {
	if x != nil {
		return x.CommunicationChannels
	}
	return nil
}

func (x *CommunicationChannelsResponse) GetColmenaStorageCommunicationChannel() []*ColmenaStorageCommunicationChannel {
	if x != nil {
		return x.ColmenaStorageCommunicationChannel
	}
	return nil
}

type CommunicationChannel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *CommunicationChannel) Reset() {
	*x = CommunicationChannel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_routes_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommunicationChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunicationChannel) ProtoMessage() {}

func (x *CommunicationChannel) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_routes_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunicationChannel.ProtoReflect.Descriptor instead.
func (*CommunicationChannel) Descriptor() ([]byte, []int) {
	return file_grpc_routes_proto_rawDescGZIP(), []int{6}
}

func (x *CommunicationChannel) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *CommunicationChannel) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// DCP brokered queue
type ColmenaStorageCommunicationChannel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ColmenaStorageCommunicationChannel) Reset() {
	*x = ColmenaStorageCommunicationChannel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_routes_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColmenaStorageCommunicationChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColmenaStorageCommunicationChannel) ProtoMessage() {}

func (x *ColmenaStorageCommunicationChannel) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_routes_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColmenaStorageCommunicationChannel.ProtoReflect.Descriptor instead.
func (*ColmenaStorageCommunicationChannel) Descriptor() ([]byte, []int) {
	return file_grpc_routes_proto_rawDescGZIP(), []int{7}
}

func (x *ColmenaStorageCommunicationChannel) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type RegisterCommunicationChannelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Host string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port int32  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *RegisterCommunicationChannelRequest) Reset() {
	*x = RegisterCommunicationChannelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_routes_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterCommunicationChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCommunicationChannelRequest) ProtoMessage() {}

func (x *RegisterCommunicationChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_routes_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCommunicationChannelRequest.ProtoReflect.Descriptor instead.
func (*RegisterCommunicationChannelRequest) Descriptor() ([]byte, []int) {
	return file_grpc_routes_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterCommunicationChannelRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RegisterCommunicationChannelRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RegisterCommunicationChannelRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type ServiceDescriptionId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ServiceDescriptionId) Reset() {
	*x = ServiceDescriptionId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_routes_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceDescriptionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDescriptionId) ProtoMessage() {}

func (x *ServiceDescriptionId) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_routes_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDescriptionId.ProtoReflect.Descriptor instead.
func (*ServiceDescriptionId) Descriptor() ([]byte, []int) {
	return file_grpc_routes_proto_rawDescGZIP(), []int{9}
}

func (x *ServiceDescriptionId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ServiceDescription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                    *ServiceDescriptionId   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleDefinitions       []*RoleDefinition       `protobuf:"bytes,2,rep,name=roleDefinitions,proto3" json:"roleDefinitions,omitempty"`
	DockerRoleDefinitions []*DockerRoleDefinition `protobuf:"bytes,3,rep,name=dockerRoleDefinitions,proto3" json:"dockerRoleDefinitions,omitempty"`
	Kpis                  []*Kpi                  `protobuf:"bytes,4,rep,name=kpis,proto3" json:"kpis,omitempty"`
}

func (x *ServiceDescription) Reset() {
	*x = ServiceDescription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_routes_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDescription) ProtoMessage() {}

func (x *ServiceDescription) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_routes_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDescription.ProtoReflect.Descriptor instead.
func (*ServiceDescription) Descriptor() ([]byte, []int) {
	return file_grpc_routes_proto_rawDescGZIP(), []int{10}
}

func (x *ServiceDescription) GetId() *ServiceDescriptionId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ServiceDescription) GetRoleDefinitions() []*RoleDefinition {
	if x != nil {
		return x.RoleDefinitions
	}
	return nil
}

func (x *ServiceDescription) GetDockerRoleDefinitions() []*DockerRoleDefinition {
	if x != nil {
		return x.DockerRoleDefinitions
	}
	return nil
}

func (x *ServiceDescription) GetKpis() []*Kpi {
	if x != nil {
		return x.Kpis
	}
	return nil
}

type DockerRoleDefinition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ImageId              string                `protobuf:"bytes,2,opt,name=imageId,proto3" json:"imageId,omitempty"`
	HardwareRequirements []HardwareRequirement `protobuf:"varint,3,rep,packed,name=hardwareRequirements,proto3,enum=HardwareRequirement" json:"hardwareRequirements,omitempty"`
	Kpis                 []*Kpi                `protobuf:"bytes,4,rep,name=kpis,proto3" json:"kpis,omitempty"`
}

func (x *DockerRoleDefinition) Reset() {
	*x = DockerRoleDefinition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_routes_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DockerRoleDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerRoleDefinition) ProtoMessage() {}

func (x *DockerRoleDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_routes_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerRoleDefinition.ProtoReflect.Descriptor instead.
func (*DockerRoleDefinition) Descriptor() ([]byte, []int) {
	return file_grpc_routes_proto_rawDescGZIP(), []int{11}
}

func (x *DockerRoleDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DockerRoleDefinition) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *DockerRoleDefinition) GetHardwareRequirements() []HardwareRequirement {
	if x != nil {
		return x.HardwareRequirements
	}
	return nil
}

func (x *DockerRoleDefinition) GetKpis() []*Kpi {
	if x != nil {
		return x.Kpis
	}
	return nil
}

type RoleDefinition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClassName            string                `protobuf:"bytes,2,opt,name=className,proto3" json:"className,omitempty"`
	HardwareRequirements []HardwareRequirement `protobuf:"varint,3,rep,packed,name=hardwareRequirements,proto3,enum=HardwareRequirement" json:"hardwareRequirements,omitempty"`
	Kpis                 []*Kpi                `protobuf:"bytes,4,rep,name=kpis,proto3" json:"kpis,omitempty"`
}

func (x *RoleDefinition) Reset() {
	*x = RoleDefinition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_routes_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleDefinition) ProtoMessage() {}

func (x *RoleDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_routes_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleDefinition.ProtoReflect.Descriptor instead.
func (*RoleDefinition) Descriptor() ([]byte, []int) {
	return file_grpc_routes_proto_rawDescGZIP(), []int{12}
}

func (x *RoleDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoleDefinition) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *RoleDefinition) GetHardwareRequirements() []HardwareRequirement {
	if x != nil {
		return x.HardwareRequirements
	}
	return nil
}

func (x *RoleDefinition) GetKpis() []*Kpi {
	if x != nil {
		return x.Kpis
	}
	return nil
}

type Kpi struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Kpi) Reset() {
	*x = Kpi{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_routes_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kpi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kpi) ProtoMessage() {}

func (x *Kpi) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_routes_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kpi.ProtoReflect.Descriptor instead.
func (*Kpi) Descriptor() ([]byte, []int) {
	return file_grpc_routes_proto_rawDescGZIP(), []int{13}
}

func (x *Kpi) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_grpc_routes_proto protoreflect.FileDescriptor

var file_grpc_routes_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x38, 0x0a, 0x0e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x79, 0x0a, 0x15, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x38, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x24, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x29, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x30, 0x0a, 0x1c, 0x43, 0x6f, 0x6d, 0x6d, 0x75,
	0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0xf3, 0x01, 0x0a, 0x1d, 0x43, 0x6f,
	0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x4b, 0x0a,
	0x15, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x52, 0x15, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x12, 0x73, 0x0a, 0x22, 0x63, 0x6f,
	0x6c, 0x6d, 0x65, 0x6e, 0x61, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x6d,
	0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x43, 0x6f, 0x6c, 0x6d, 0x65, 0x6e, 0x61,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x22, 0x63, 0x6f, 0x6c,
	0x6d, 0x65, 0x6e, 0x61, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x75,
	0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x22,
	0x3e, 0x0a, 0x14, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22,
	0x36, 0x0a, 0x22, 0x43, 0x6f, 0x6c, 0x6d, 0x65, 0x6e, 0x61, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x5f, 0x0a, 0x23, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x2c, 0x0a, 0x14, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xdd, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x0f, 0x72, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x66, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x52, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0f,
	0x72, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x4b, 0x0a, 0x15, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x15, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x6f, 0x6c,
	0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x04,
	0x6b, 0x70, 0x69, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x4b, 0x70, 0x69,
	0x52, 0x04, 0x6b, 0x70, 0x69, 0x73, 0x22, 0xa4, 0x01, 0x0a, 0x14, 0x44, 0x6f, 0x63, 0x6b, 0x65,
	0x72, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x48, 0x0a, 0x14, 0x68, 0x61, 0x72,
	0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61,
	0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x14, 0x68,
	0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x04, 0x6b, 0x70, 0x69, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x04, 0x2e, 0x4b, 0x70, 0x69, 0x52, 0x04, 0x6b, 0x70, 0x69, 0x73, 0x22, 0xa2, 0x01,
	0x0a, 0x0e, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x48,
	0x0a, 0x14, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x48,
	0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x14, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x04, 0x6b, 0x70, 0x69, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x4b, 0x70, 0x69, 0x52, 0x04, 0x6b, 0x70,
	0x69, 0x73, 0x22, 0x1b, 0x0a, 0x03, 0x4b, 0x70, 0x69, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2a,
	0x3c, 0x0a, 0x0d, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1c, 0x0a, 0x18, 0x47, 0x52, 0x45, 0x41, 0x54, 0x45, 0x52, 0x5f, 0x54, 0x48, 0x41, 0x4e,
	0x5f, 0x4f, 0x52, 0x5f, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x5f, 0x54, 0x4f, 0x10, 0x00, 0x12, 0x0d,
	0x0a, 0x09, 0x4c, 0x45, 0x53, 0x53, 0x5f, 0x54, 0x48, 0x41, 0x4e, 0x10, 0x01, 0x2a, 0x2a, 0x0a,
	0x13, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x41, 0x4d, 0x45, 0x52, 0x41, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x43, 0x50, 0x55, 0x10, 0x01, 0x2a, 0x2f, 0x0a, 0x08, 0x54, 0x69, 0x6d,
	0x65, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x45, 0x43, 0x4f, 0x4e, 0x44, 0x53,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x49, 0x4e, 0x55, 0x54, 0x45, 0x53, 0x10, 0x01, 0x12,
	0x09, 0x0a, 0x05, 0x48, 0x4f, 0x55, 0x52, 0x53, 0x10, 0x02, 0x32, 0xa7, 0x04, 0x0a, 0x0f, 0x43,
	0x6f, 0x6c, 0x6d, 0x65, 0x6e, 0x61, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x30,
	0x0a, 0x05, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x0f, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x32, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x12, 0x11, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x12,
	0x0f, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x34, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x3c,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x13, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x30, 0x01, 0x12, 0x4a, 0x0a,
	0x19, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54, 0x6f, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x13, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x30, 0x01, 0x12, 0x39, 0x0a, 0x0a, 0x41, 0x64, 0x64,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x13, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x3e, 0x0a, 0x0d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x15, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x42, 0x27, 0x0a, 0x1d, 0x65, 0x73, 0x2e, 0x62, 0x73, 0x63, 0x2e, 0x63,
	0x6f, 0x6c, 0x6d, 0x65, 0x6e, 0x61, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x67, 0x75, 0x69, 0x64, 0x65, 0x5a, 0x06, 0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_routes_proto_rawDescOnce sync.Once
	file_grpc_routes_proto_rawDescData = file_grpc_routes_proto_rawDesc
)

func file_grpc_routes_proto_rawDescGZIP() []byte {
	file_grpc_routes_proto_rawDescOnce.Do(func() {
		file_grpc_routes_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_routes_proto_rawDescData)
	})
	return file_grpc_routes_proto_rawDescData
}

var file_grpc_routes_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_grpc_routes_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_grpc_routes_proto_goTypes = []interface{}{
	(ThresholdType)(0),                          // 0: ThresholdType
	(HardwareRequirement)(0),                    // 1: HardwareRequirement
	(TimeUnit)(0),                               // 2: TimeUnit
	(*StorageRequest)(nil),                      // 3: StorageRequest
	(*MetricsStorageRequest)(nil),               // 4: MetricsStorageRequest
	(*GetStoredRequest)(nil),                    // 5: GetStoredRequest
	(*GetStoredResponse)(nil),                   // 6: GetStoredResponse
	(*CommunicationChannelsRequest)(nil),        // 7: CommunicationChannelsRequest
	(*CommunicationChannelsResponse)(nil),       // 8: CommunicationChannelsResponse
	(*CommunicationChannel)(nil),                // 9: CommunicationChannel
	(*ColmenaStorageCommunicationChannel)(nil),  // 10: ColmenaStorageCommunicationChannel
	(*RegisterCommunicationChannelRequest)(nil), // 11: RegisterCommunicationChannelRequest
	(*ServiceDescriptionId)(nil),                // 12: ServiceDescriptionId
	(*ServiceDescription)(nil),                  // 13: ServiceDescription
	(*DockerRoleDefinition)(nil),                // 14: DockerRoleDefinition
	(*RoleDefinition)(nil),                      // 15: RoleDefinition
	(*Kpi)(nil),                                 // 16: Kpi
	(*timestamp.Timestamp)(nil),                 // 17: google.protobuf.Timestamp
	(*empty.Empty)(nil),                         // 18: google.protobuf.Empty
}
var file_grpc_routes_proto_depIdxs = []int32{
	17, // 0: MetricsStorageRequest.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 1: CommunicationChannelsResponse.communicationChannels:type_name -> CommunicationChannel
	10, // 2: CommunicationChannelsResponse.colmenaStorageCommunicationChannel:type_name -> ColmenaStorageCommunicationChannel
	12, // 3: ServiceDescription.id:type_name -> ServiceDescriptionId
	15, // 4: ServiceDescription.roleDefinitions:type_name -> RoleDefinition
	14, // 5: ServiceDescription.dockerRoleDefinitions:type_name -> DockerRoleDefinition
	16, // 6: ServiceDescription.kpis:type_name -> Kpi
	1,  // 7: DockerRoleDefinition.hardwareRequirements:type_name -> HardwareRequirement
	16, // 8: DockerRoleDefinition.kpis:type_name -> Kpi
	1,  // 9: RoleDefinition.hardwareRequirements:type_name -> HardwareRequirement
	16, // 10: RoleDefinition.kpis:type_name -> Kpi
	3,  // 11: ColmenaPlatform.Store:input_type -> StorageRequest
	5,  // 12: ColmenaPlatform.GetStored:input_type -> GetStoredRequest
	3,  // 13: ColmenaPlatform.Publish:input_type -> StorageRequest
	5,  // 14: ColmenaPlatform.Subscribe:input_type -> GetStoredRequest
	5,  // 15: ColmenaPlatform.GetSubscriptionItem:input_type -> GetStoredRequest
	18, // 16: ColmenaPlatform.GetAllServices:input_type -> google.protobuf.Empty
	18, // 17: ColmenaPlatform.SubscribeToServiceChanges:input_type -> google.protobuf.Empty
	13, // 18: ColmenaPlatform.AddService:input_type -> ServiceDescription
	12, // 19: ColmenaPlatform.RemoveService:input_type -> ServiceDescriptionId
	18, // 20: ColmenaPlatform.Store:output_type -> google.protobuf.Empty
	6,  // 21: ColmenaPlatform.GetStored:output_type -> GetStoredResponse
	18, // 22: ColmenaPlatform.Publish:output_type -> google.protobuf.Empty
	6,  // 23: ColmenaPlatform.Subscribe:output_type -> GetStoredResponse
	6,  // 24: ColmenaPlatform.GetSubscriptionItem:output_type -> GetStoredResponse
	13, // 25: ColmenaPlatform.GetAllServices:output_type -> ServiceDescription
	13, // 26: ColmenaPlatform.SubscribeToServiceChanges:output_type -> ServiceDescription
	18, // 27: ColmenaPlatform.AddService:output_type -> google.protobuf.Empty
	18, // 28: ColmenaPlatform.RemoveService:output_type -> google.protobuf.Empty
	20, // [20:29] is the sub-list for method output_type
	11, // [11:20] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_grpc_routes_proto_init() }
func file_grpc_routes_proto_init() {
	if File_grpc_routes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_routes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StorageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_routes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricsStorageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_routes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStoredRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_routes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStoredResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_routes_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunicationChannelsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_routes_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunicationChannelsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_routes_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommunicationChannel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_routes_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColmenaStorageCommunicationChannel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_routes_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterCommunicationChannelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_routes_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceDescriptionId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_routes_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceDescription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_routes_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DockerRoleDefinition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_routes_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleDefinition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_routes_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kpi); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_routes_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_routes_proto_goTypes,
		DependencyIndexes: file_grpc_routes_proto_depIdxs,
		EnumInfos:         file_grpc_routes_proto_enumTypes,
		MessageInfos:      file_grpc_routes_proto_msgTypes,
	}.Build()
	File_grpc_routes_proto = out.File
	file_grpc_routes_proto_rawDesc = nil
	file_grpc_routes_proto_goTypes = nil
	file_grpc_routes_proto_depIdxs = nil
}
